### ISSUE TITLE
Can't download Pxper from the site

### ISSUE THREAD

**Issue by alex-kononovich** [Pxper/Pxper#1]
(I know that's not the most appropriate place to report that, but I can't find any contact information on the site itself)

When I click "Download", I get blank page. Here is what's going on:
![screen shot 2016-09-15 at 12 08 13](https://cloud.githubusercontent.com/assets/12843/18544704/953c14c8-7b3e-11e6-8a7d-bc28224b2d15.png)

**Comment by DmitrySikorsky** [comment]
Thanks! I will fix that, now you can download it using this link: http://pxper.com/content/files/pxper_1.0.0.0_setup.zip

(Problem is that .exe files are blocked or something like that, need to check.)

**Comment by alex-kononovich** [comment]
Thanks a lot!

**Comment by DmitrySikorsky** [comment]
The link is fixed now.
